In [1]:
import os
print(os.getcwd())

C:\Users\sunil\projects\used car price prediction

In [27]:
import pandas as pd
import numpy as np

In [28]:
car1 = pd.read_csv("used_cars_data.csv")

In [31]:
car2 = pd.read_csv("cardekho_dataset.csv")

In [34]:
car1.shape

(7253, 14)

In [35]:
car2.shape

(15411, 14)

In [37]:
car1.columns

Index(['S.No.', 'Name', 'Location', 'Year', 'Kilometers_Driven', 'Fuel_Type',
       'Transmission', 'Owner_Type', 'Mileage', 'Engine', 'Power', 'Seats',
       'New_Price', 'Price'],
      dtype='object')

In [38]:
car2.columns

Index(['Unnamed: 0', 'car_name', 'brand', 'model', 'vehicle_age', 'km_driven',
       'seller_type', 'fuel_type', 'transmission_type', 'mileage', 'engine',
       'max_power', 'seats', 'selling_price'],
      dtype='object')

In [39]:
car1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7253 entries, 0 to 7252
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   S.No.              7253 non-null   int64
 1   Name               7253 non-null   object
 2   Location           7253 non-null   object
 3   Year               7253 non-null   int64
 4   Kilometers_Driven  7253 non-null   int64
 5   Fuel_Type          7253 non-null   object
 6   Transmission       7253 non-null   object
 7   Owner_Type         7253 non-null   object
 8   Mileage            7251 non-null   object
 9   Engine             7207 non-null   object
 10  Power              7207 non-null   object
 11  Seats              7200 non-null   float64
 12  New_Price          1006 non-null   object
 13  Price              6019 non-null   float64
dtypes: float64(2), int64(3), object(9)
memory usage: 793.4+ KB

In [40]:
car2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15411 entries, 0 to 15410
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         15411 non-null  int64
 1   car_name           15411 non-null  object
 2   brand              15411 non-null  object
 3   model              15411 non-null  object
 4   vehicle_age        15411 non-null  int64
 5   km_driven          15411 non-null  int64
 6   seller_type        15411 non-null  object
 7   fuel_type          15411 non-null  object
 8   transmission_type  15411 non-null  object
 9   mileage            15411 non-null  float64
 10  engine             15411 non-null  int64
 11  max_power          15411 non-null  float64
 12  seats              15411 non-null  int64
 13  selling_price      15411 non-null  int64
dtypes: float64(2), int64(6), object(6)
memory usage: 1.6+ MB

In [41]:
car1.head()

,S.No.,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
0,0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.6 km/kg,998 CC,58.16 bhp,5.0,NaN,1.75
1,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67 kmpl,1582 CC,126.2 bhp,5.0,NaN,12.50
2,2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,18.2 kmpl,1199 CC,88.7 bhp,5.0,8.61 Lakh,4.50
3,3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77 kmpl,1248 CC,88.76 bhp,7.0,NaN,6.00
4,4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,15.2 kmpl,1968 CC,140.8 bhp,5.0,NaN,17.74

In [42]:
car2.head()

,Unnamed: 0,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,0,Maruti Alto,Maruti,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000
1,1,Hyundai Grand,Hyundai,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000
2,2,Hyundai i20,Hyundai,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000
3,3,Maruti Alto,Maruti,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,4,Ford Ecosport,Ford,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000

In [43]:
car1[['Price']].head()

   Price
0   1.75
1  12.50
2   4.50
3   6.00
4  17.74

In [44]:
car2[['selling_price']].head()

   selling_price
0         120000
1         550000
2         215000
3         226000
4         570000

In [45]:
car1['price_inr'] = car1['Price'] * 100000

In [46]:
car1[['Price', 'price_inr']].head()

   Price  price_inr
0   1.75   175000.0
1  12.50  1250000.0
2   4.50   450000.0
3   6.00   600000.0
4  17.74  1774000.0

In [47]:
car2['price_inr'] = car2['selling_price']

In [48]:
car2[['selling_price', 'price_inr']].head()

   selling_price  price_inr
0         120000     120000
1         550000     550000
2         215000     215000
3         226000     226000
4         570000     570000

In [49]:
car1.drop(columns=['Price'], inplace=True)
car2.drop(columns=['selling_price'], inplace=True)

In [50]:
car1.drop(columns=['S.No.'], inplace=True)
car2.drop(columns=['Unnamed: 0'], inplace=True)

In [51]:
car1 = car1.rename(columns={
    'Name': 'car_name',
    'Location': 'location',
    'Year': 'year',
    'Kilometers_Driven': 'km_driven',
    'Fuel_Type': 'fuel_type',
    'Transmission': 'transmission_type',
    'Owner_Type': 'owner_type',
    'Mileage': 'mileage',
    'Engine': 'engine',
    'Power': 'max_power',
    'Seats': 'seats',
    'New_Price': 'new_price'
})

In [52]:
car1['vehicle_age'] = 2024 - car1['year']

In [53]:
car1[['year', 'vehicle_age']].head()

   year  vehicle_age
0  2010           14
1  2015            9
2  2011           13
3  2012           12
4  2013           11

In [54]:
car1.drop(columns=['year'], inplace=True)

In [55]:
set(car1.columns) - set(car2.columns)

{'location', 'new_price', 'owner_type'}

In [56]:
set(car2.columns) - set(car1.columns)

{'brand', 'model', 'seller_type'}

In [59]:
# add missing columns to car1
car1['brand'] = np.nan
car1['model'] = np.nan
car1['seller_type'] = np.nan

In [60]:
# add missing columns to car2
car2['location'] = np.nan
car2['new_price'] = np.nan
car2['owner_type'] = np.nan

In [61]:
common_cols = car1.columns
car2 = car2[common_cols]

In [62]:
df = pd.concat([car1, car2], ignore_index=True)

In [63]:
df.shape

(22664, 16)

In [64]:
df.head()

,car_name,location,km_driven,fuel_type,transmission_type,owner_type,mileage,engine,max_power,seats,new_price,price_inr,vehicle_age,brand,model,seller_type
0,Maruti Wagon R LXI CNG,Mumbai,72000,CNG,Manual,First,26.6 km/kg,998 CC,58.16 bhp,5.0,NaN,175000.0,14,NaN,NaN,NaN
1,Hyundai Creta 1.6 CRDi SX Option,Pune,41000,Diesel,Manual,First,19.67 kmpl,1582 CC,126.2 bhp,5.0,NaN,1250000.0,9,NaN,NaN,NaN
2,Honda Jazz V,Chennai,46000,Petrol,Manual,First,18.2 kmpl,1199 CC,88.7 bhp,5.0,8.61 Lakh,450000.0,13,NaN,NaN,NaN
3,Maruti Ertiga VDI,Chennai,87000,Diesel,Manual,First,20.77 kmpl,1248 CC,88.76 bhp,7.0,NaN,600000.0,12,NaN,NaN,NaN
4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,40670,Diesel,Automatic,Second,15.2 kmpl,1968 CC,140.8 bhp,5.0,NaN,1774000.0,11,NaN,NaN,NaN

In [65]:
df.tail()

,car_name,location,km_driven,fuel_type,transmission_type,owner_type,mileage,engine,max_power,seats,new_price,price_inr,vehicle_age,brand,model,seller_type
22659,Hyundai i10,NaN,10723,Petrol,Manual,NaN,19.81,1086,68.05,5.0,NaN,250000.0,9,Hyundai,i10,Dealer
22660,Maruti Ertiga,NaN,18000,Petrol,Manual,NaN,17.5,1373,91.1,7.0,NaN,925000.0,2,Maruti,Ertiga,Dealer
22661,Skoda Rapid,NaN,67000,Diesel,Manual,NaN,21.14,1498,103.52,5.0,NaN,425000.0,6,Skoda,Rapid,Dealer
22662,Mahindra XUV500,NaN,3800000,Diesel,Manual,NaN,16.0,2179,140.0,7.0,NaN,1225000.0,5,Mahindra,XUV500,Dealer
22663,Honda City,NaN,13000,Petrol,Automatic,NaN,18.0,1497,117.6,5.0,NaN,1200000.0,2,Honda,City,Dealer

In [66]:
df[['brand', 'model']] = df['car_name'].str.split(' ', n=1, expand=True)

In [67]:
df.head()

,car_name,location,km_driven,fuel_type,transmission_type,owner_type,mileage,engine,max_power,seats,new_price,price_inr,vehicle_age,brand,model,seller_type
0,Maruti Wagon R LXI CNG,Mumbai,72000,CNG,Manual,First,26.6 km/kg,998 CC,58.16 bhp,5.0,NaN,175000.0,14,Maruti,Wagon R LXI CNG,NaN
1,Hyundai Creta 1.6 CRDi SX Option,Pune,41000,Diesel,Manual,First,19.67 kmpl,1582 CC,126.2 bhp,5.0,NaN,1250000.0,9,Hyundai,Creta 1.6 CRDi SX Option,NaN
2,Honda Jazz V,Chennai,46000,Petrol,Manual,First,18.2 kmpl,1199 CC,88.7 bhp,5.0,8.61 Lakh,450000.0,13,Honda,Jazz V,NaN
3,Maruti Ertiga VDI,Chennai,87000,Diesel,Manual,First,20.77 kmpl,1248 CC,88.76 bhp,7.0,NaN,600000.0,12,Maruti,Ertiga VDI,NaN
4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,40670,Diesel,Automatic,Second,15.2 kmpl,1968 CC,140.8 bhp,5.0,NaN,1774000.0,11,Audi,A4 New 2.0 TDI Multitronic,NaN

In [68]:
df.tail()

,car_name,location,km_driven,fuel_type,transmission_type,owner_type,mileage,engine,max_power,seats,new_price,price_inr,vehicle_age,brand,model,seller_type
22659,Hyundai i10,NaN,10723,Petrol,Manual,NaN,19.81,1086,68.05,5.0,NaN,250000.0,9,Hyundai,i10,Dealer
22660,Maruti Ertiga,NaN,18000,Petrol,Manual,NaN,17.5,1373,91.1,7.0,NaN,925000.0,2,Maruti,Ertiga,Dealer
22661,Skoda Rapid,NaN,67000,Diesel,Manual,NaN,21.14,1498,103.52,5.0,NaN,425000.0,6,Skoda,Rapid,Dealer
22662,Mahindra XUV500,NaN,3800000,Diesel,Manual,NaN,16.0,2179,140.0,7.0,NaN,1225000.0,5,Mahindra,XUV500,Dealer
22663,Honda City,NaN,13000,Petrol,Automatic,NaN,18.0,1497,117.6,5.0,NaN,1200000.0,2,Honda,City,Dealer

In [69]:
cat_cols = ['location', 'owner_type', 'seller_type']

for col in cat_cols:
    df[col] = df[col].fillna('Unknown')

In [70]:
df.isna().sum()

car_name                 0
location                 0
km_driven                0
fuel_type                0
transmission_type        0
owner_type               0
mileage                  2
engine                  46
max_power               46
seats                   53
new_price            21658
price_inr             1234
vehicle_age              0
brand                    0
model                    0
seller_type              0
dtype: int64

In [71]:
df = df.dropna(subset=['price_inr'])

In [72]:
df.isna().sum()

car_name                 0
location                 0
km_driven                0
fuel_type                0
transmission_type        0
owner_type               0
mileage                  2
engine                  36
max_power               36
seats                   42
new_price            20606
price_inr                0
vehicle_age              0
brand                    0
model                    0
seller_type              0
dtype: int64

In [73]:
df = df.drop(columns=['new_price'])

In [74]:
df.columns

Index(['car_name', 'location', 'km_driven', 'fuel_type', 'transmission_type',
       'owner_type', 'mileage', 'engine', 'max_power', 'seats', 'price_inr',
       'vehicle_age', 'brand', 'model', 'seller_type'],
      dtype='object')

In [75]:
df['mileage'] = df['mileage'].str.extract('(\d+\.?\d*)').astype(float)
df['engine'] = df['engine'].str.extract('(\d+\.?\d*)').astype(float)
df['max_power'] = df['max_power'].str.extract('(\d+\.?\d*)').astype(float)

In [76]:
df[['mileage','engine','max_power']].head()

   mileage  engine  max_power
0    26.60   998.0      58.16
1    19.67  1582.0     126.20
2    18.20  1199.0      88.70
3    20.77  1248.0      88.76
4    15.20  1968.0     140.80

In [77]:
num_cols = ['mileage', 'engine', 'max_power', 'seats']

for col in num_cols:
    df[col] = df[col].fillna(df[col].median())

In [78]:
df.isna().sum()

car_name             0
location             0
km_driven            0
fuel_type            0
transmission_type    0
owner_type           0
mileage              0
engine               0
max_power            0
seats                0
price_inr            0
vehicle_age          0
brand                0
model                0
seller_type          0
dtype: int64

In [79]:
X = df.drop(columns=['price_inr', 'car_name'])
y = df['price_inr']

In [80]:
X.head()

,location,km_driven,fuel_type,transmission_type,owner_type,mileage,engine,max_power,seats,vehicle_age,brand,model,seller_type
0,Mumbai,72000,CNG,Manual,First,26.60,998.0,58.16,5.0,14,Maruti,Wagon R LXI CNG,Unknown
1,Pune,41000,Diesel,Manual,First,19.67,1582.0,126.20,5.0,9,Hyundai,Creta 1.6 CRDi SX Option,Unknown
2,Chennai,46000,Petrol,Manual,First,18.20,1199.0,88.70,5.0,13,Honda,Jazz V,Unknown
3,Chennai,87000,Diesel,Manual,First,20.77,1248.0,88.76,7.0,12,Maruti,Ertiga VDI,Unknown
4,Coimbatore,40670,Diesel,Automatic,Second,15.20,1968.0,140.80,5.0,11,Audi,A4 New 2.0 TDI Multitronic,Unknown

In [81]:
!pip install catboost

Collecting catboost
  Downloading catboost-1.2.10-cp313-cp313-win_amd64.whl.metadata (1.5 kB)
Collecting graphviz (from catboost)
  Downloading graphviz-0.21-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: matplotlib in c:\users\sunil\anaconda3\lib\site-packages (from catboost) (3.10.0)
Requirement already satisfied: numpy<3.0,>=1.16.0 in c:\users\sunil\anaconda3\lib\site-packages (from catboost) (2.1.3)
Requirement already satisfied: pandas<4.0,>=0.24 in c:\users\sunil\anaconda3\lib\site-packages (from catboost) (2.2.3)
Requirement already satisfied: scipy in c:\users\sunil\anaconda3\lib\site-packages (from catboost) (1.15.3)
Requirement already satisfied: plotly in c:\users\sunil\anaconda3\lib\site-packages (from catboost) (5.24.1)
Requirement already satisfied: six in c:\users\sunil\anaconda3\lib\site-packages (from catboost) (1.17.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\sunil\anaconda3\lib\site-packages (from pandas<4.0,>=0.24->catboost) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\sunil\anaconda3\lib\site-packages (from pandas<4.0,>=0.24->catboost) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\sunil\anaconda3\lib\site-packages (from pandas<4.0,>=0.24->catboost) (2025.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\sunil\anaconda3\lib\site-packages (from matplotlib->catboost) (1.3.1)
Requirement already satisfied: cycler>=0.10 in c:\users\sunil\anaconda3\lib\site-packages (from matplotlib->catboost) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\sunil\anaconda3\lib\site-packages (from matplotlib->catboost) (4.55.3)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\sunil\anaconda3\lib\site-packages (from matplotlib->catboost) (1.4.8)
Requirement already satisfied: packaging>=20.0 in c:\users\sunil\anaconda3\lib\site-packages (from matplotlib->catboost) (24.2)
Requirement already satisfied: pillow>=8 in c:\users\sunil\anaconda3\lib\site-packages (from matplotlib->catboost) (11.1.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\sunil\anaconda3\lib\site-packages (from matplotlib->catboost) (3.2.0)
Requirement already satisfied: tenacity>=6.2.0 in c:\users\sunil\anaconda3\lib\site-packages (from plotly->catboost) (9.0.0)
Downloading catboost-1.2.10-cp313-cp313-win_amd64.whl (100.2 MB)
   ---------------------------------------- 0.0/100.2 MB ? eta -:--:--
   ---------------------------------------- 0.8/100.2 MB 3.7 MB/s eta 0:00:27
    --------------------------------------- 1.3/100.2 MB 3.7 MB/s eta 0:00:28
    --------------------------------------- 2.1/100.2 MB 3.7 MB/s eta 0:00:27
   - -------------------------------------- 2.9/100.2 MB 3.7 MB/s eta 0:00:27
   - -------------------------------------- 3.7/100.2 MB 3.7 MB/s eta 0:00:27
   - -------------------------------------- 4.5/100.2 MB 3.7 MB/s eta 0:00:27
   -- ------------------------------------- 5.2/100.2 MB 3.7 MB/s eta 0:00:26
   -- ------------------------------------- 6.0/100.2 MB 3.7 MB/s eta 0:00:26
   -- ------------------------------------- 6.8/100.2 MB 3.7 MB/s eta 0:00:26
   --- ------------------------------------ 7.6/100.2 MB 3.7 MB/s eta 0:00:26
   --- ------------------------------------ 8.4/100.2 MB 3.7 MB/s eta 0:00:26
   --- ------------------------------------ 9.2/100.2 MB 3.7 MB/s eta 0:00:25
   --- ------------------------------------ 10.0/100.2 MB 3.7 MB/s eta 0:00:25
   ---- ----------------------------------- 10.5/100.2 MB 3.7 MB/s eta 0:00:25
   ---- ----------------------------------- 11.3/100.2 MB 3.7 MB/s eta 0:00:25
   ---- ----------------------------------- 12.1/100.2 MB 3.7 MB/s eta 0:00:25
   ----- ---------------------------------- 12.8/100.2 MB 3.7 MB/s eta 0:00:24
   ----- ---------------------------------- 13.6/100.2 MB 3.7 MB/s eta 0:00:24
   ----- ---------------------------------- 14.4/100.2 MB 3.7 MB/s eta 0:00:24
   ------ --------------------------------- 15.2/100.2 MB 3.7 MB/s eta 0:00:24
   ------ --------------------------------- 16.0/100.2 MB 3.7 MB/s eta 0:00:24
   ------ --------------------------------- 16.8/100.2 MB 3.7 MB/s eta 0:00:23
   ------- -------------------------------- 17.6/100.2 MB 3.7 MB/s eta 0:00:23
   ------- -------------------------------- 18.4/100.2 MB 3.7 MB/s eta 0:00:23
   ------- -------------------------------- 18.9/100.2 MB 3.7 MB/s eta 0:00:23
   ------- -------------------------------- 19.7/100.2 MB 3.7 MB/s eta 0:00:23
   -------- ------------------------------- 20.4/100.2 MB 3.7 MB/s eta 0:00:22
   -------- ------------------------------- 21.2/100.2 MB 3.7 MB/s eta 0:00:22
   -------- ------------------------------- 22.0/100.2 MB 3.7 MB/s eta 0:00:22
   --------- ------------------------------ 22.8/100.2 MB 3.7 MB/s eta 0:00:22
   --------- ------------------------------ 23.6/100.2 MB 3.7 MB/s eta 0:00:21
   --------- ------------------------------ 24.1/100.2 MB 3.7 MB/s eta 0:00:21
   --------- ------------------------------ 24.9/100.2 MB 3.7 MB/s eta 0:00:21
   ---------- ----------------------------- 25.7/100.2 MB 3.7 MB/s eta 0:00:21
   ---------- ----------------------------- 26.5/100.2 MB 3.7 MB/s eta 0:00:21
   ---------- ----------------------------- 27.3/100.2 MB 3.7 MB/s eta 0:00:20
   ----------- ---------------------------- 28.0/100.2 MB 3.7 MB/s eta 0:00:20
   ----------- ---------------------------- 28.8/100.2 MB 3.7 MB/s eta 0:00:20
   ----------- ---------------------------- 29.6/100.2 MB 3.7 MB/s eta 0:00:20
   ------------ --------------------------- 30.4/100.2 MB 3.7 MB/s eta 0:00:20
   ------------ --------------------------- 31.2/100.2 MB 3.7 MB/s eta 0:00:19
   ------------ --------------------------- 32.0/100.2 MB 3.7 MB/s eta 0:00:19
   ------------ --------------------------- 32.5/100.2 MB 3.7 MB/s eta 0:00:19
   ------------- -------------------------- 33.3/100.2 MB 3.7 MB/s eta 0:00:19
   ------------- -------------------------- 34.1/100.2 MB 3.7 MB/s eta 0:00:19
   ------------- -------------------------- 34.9/100.2 MB 3.7 MB/s eta 0:00:18
   -------------- ------------------------- 35.7/100.2 MB 3.7 MB/s eta 0:00:18
   -------------- ------------------------- 36.4/100.2 MB 3.7 MB/s eta 0:00:18
   -------------- ------------------------- 37.2/100.2 MB 3.7 MB/s eta 0:00:18
   --------------- ------------------------ 38.0/100.2 MB 3.7 MB/s eta 0:00:18
   --------------- ------------------------ 38.8/100.2 MB 3.7 MB/s eta 0:00:17
   --------------- ------------------------ 39.6/100.2 MB 3.7 MB/s eta 0:00:17
   ---------------- ----------------------- 40.4/100.2 MB 3.7 MB/s eta 0:00:17
   ---------------- ----------------------- 41.2/100.2 MB 3.7 MB/s eta 0:00:17
   ---------------- ----------------------- 41.9/100.2 MB 3.7 MB/s eta 0:00:16
   ----------------- ---------------------- 42.7/100.2 MB 3.7 MB/s eta 0:00:16
   ----------------- ---------------------- 43.5/100.2 MB 3.7 MB/s eta 0:00:16
   ----------------- ---------------------- 44.3/100.2 MB 3.7 MB/s eta 0:00:16
   ----------------- ---------------------- 45.1/100.2 MB 3.7 MB/s eta 0:00:16
   ------------------ --------------------- 45.9/100.2 MB 3.7 MB/s eta 0:00:15
   ------------------ --------------------- 46.7/100.2 MB 3.7 MB/s eta 0:00:15
   ------------------ --------------------- 47.4/100.2 MB 3.7 MB/s eta 0:00:15
   ------------------- -------------------- 48.2/100.2 MB 3.7 MB/s eta 0:00:15
   ------------------- -------------------- 49.0/100.2 MB 3.7 MB/s eta 0:00:15
   ------------------- -------------------- 49.8/100.2 MB 3.7 MB/s eta 0:00:14
   -------------------- ------------------- 50.6/100.2 MB 3.7 MB/s eta 0:00:14
   -------------------- ------------------- 51.4/100.2 MB 3.7 MB/s eta 0:00:14
   -------------------- ------------------- 51.9/100.2 MB 3.7 MB/s eta 0:00:14
   --------------------- ------------------ 52.7/100.2 MB 3.7 MB/s eta 0:00:14
   --------------------- ------------------ 53.5/100.2 MB 3.7 MB/s eta 0:00:13
   --------------------- ------------------ 54.3/100.2 MB 3.7 MB/s eta 0:00:13
   --------------------- ------------------ 55.1/100.2 MB 3.7 MB/s eta 0:00:13
   ---------------------- ----------------- 55.6/100.2 MB 3.7 MB/s eta 0:00:13
   ---------------------- ----------------- 56.4/100.2 MB 3.7 MB/s eta 0:00:13
   ---------------------- ----------------- 57.1/100.2 MB 3.7 MB/s eta 0:00:12
   ----------------------- ---------------- 57.9/100.2 MB 3.7 MB/s eta 0:00:12
   ----------------------- ---------------- 58.7/100.2 MB 3.7 MB/s eta 0:00:12
   ----------------------- ---------------- 59.5/100.2 MB 3.7 MB/s eta 0:00:12
   ----------------------- ---------------- 60.0/100.2 MB 3.7 MB/s eta 0:00:12
   ------------------------ --------------- 60.8/100.2 MB 3.7 MB/s eta 0:00:11
   ------------------------ --------------- 61.6/100.2 MB 3.7 MB/s eta 0:00:11
   ------------------------ --------------- 62.4/100.2 MB 3.7 MB/s eta 0:00:11
   ------------------------- -------------- 63.2/100.2 MB 3.7 MB/s eta 0:00:11
   ------------------------- -------------- 64.0/100.2 MB 3.7 MB/s eta 0:00:10
   ------------------------- -------------- 64.7/100.2 MB 3.7 MB/s eta 0:00:10
   -------------------------- ------------- 65.3/100.2 MB 3.7 MB/s eta 0:00:10
   -------------------------- ------------- 66.1/100.2 MB 3.7 MB/s eta 0:00:10
   -------------------------- ------------- 66.8/100.2 MB 3.7 MB/s eta 0:00:10
   -------------------------- ------------- 67.6/100.2 MB 3.7 MB/s eta 0:00:09
   --------------------------- ------------ 68.4/100.2 MB 3.7 MB/s eta 0:00:09
   --------------------------- ------------ 69.2/100.2 MB 3.7 MB/s eta 0:00:09
   --------------------------- ------------ 70.0/100.2 MB 3.7 MB/s eta 0:00:09
   ---------------------------- ----------- 70.5/100.2 MB 3.7 MB/s eta 0:00:09
   ---------------------------- ----------- 71.3/100.2 MB 3.7 MB/s eta 0:00:08
   ---------------------------- ----------- 72.1/100.2 MB 3.7 MB/s eta 0:00:08
   ----------------------------- ---------- 72.9/100.2 MB 3.7 MB/s eta 0:00:08
   ----------------------------- ---------- 73.7/100.2 MB 3.7 MB/s eta 0:00:08
   ----------------------------- ---------- 74.4/100.2 MB 3.7 MB/s eta 0:00:08
   ------------------------------ --------- 75.2/100.2 MB 3.7 MB/s eta 0:00:07
   ------------------------------ --------- 75.8/100.2 MB 3.7 MB/s eta 0:00:07
   ------------------------------ --------- 76.5/100.2 MB 3.7 MB/s eta 0:00:07
   ------------------------------ --------- 77.3/100.2 MB 3.7 MB/s eta 0:00:07
   ------------------------------- -------- 78.1/100.2 MB 3.7 MB/s eta 0:00:07
   ------------------------------- -------- 78.9/100.2 MB 3.7 MB/s eta 0:00:06
   ------------------------------- -------- 79.7/100.2 MB 3.7 MB/s eta 0:00:06
   -------------------------------- ------- 80.5/100.2 MB 3.7 MB/s eta 0:00:06
   -------------------------------- ------- 81.0/100.2 MB 3.7 MB/s eta 0:00:06
   -------------------------------- ------- 81.8/100.2 MB 3.7 MB/s eta 0:00:06
   -------------------------------- ------- 82.6/100.2 MB 3.7 MB/s eta 0:00:05
   --------------------------------- ------ 83.4/100.2 MB 3.7 MB/s eta 0:00:05
   --------------------------------- ------ 84.1/100.2 MB 3.7 MB/s eta 0:00:05
   --------------------------------- ------ 84.9/100.2 MB 3.7 MB/s eta 0:00:05
   ---------------------------------- ----- 85.5/100.2 MB 3.7 MB/s eta 0:00:05
   ---------------------------------- ----- 86.2/100.2 MB 3.7 MB/s eta 0:00:04
   ---------------------------------- ----- 87.0/100.2 MB 3.7 MB/s eta 0:00:04
   ----------------------------------- ---- 87.8/100.2 MB 3.7 MB/s eta 0:00:04
   ----------------------------------- ---- 88.6/100.2 MB 3.7 MB/s eta 0:00:04
   ----------------------------------- ---- 89.4/100.2 MB 3.7 MB/s eta 0:00:03
   ----------------------------------- ---- 90.2/100.2 MB 3.7 MB/s eta 0:00:03
   ------------------------------------ --- 91.0/100.2 MB 3.7 MB/s eta 0:00:03
   ------------------------------------ --- 91.8/100.2 MB 3.7 MB/s eta 0:00:03
   ------------------------------------ --- 92.5/100.2 MB 3.7 MB/s eta 0:00:03
   ------------------------------------- -- 93.3/100.2 MB 3.7 MB/s eta 0:00:02
   ------------------------------------- -- 94.1/100.2 MB 3.7 MB/s eta 0:00:02
   ------------------------------------- -- 94.9/100.2 MB 3.7 MB/s eta 0:00:02
   -------------------------------------- - 95.7/100.2 MB 3.7 MB/s eta 0:00:02
   -------------------------------------- - 96.5/100.2 MB 3.7 MB/s eta 0:00:02
   -------------------------------------- - 97.3/100.2 MB 3.7 MB/s eta 0:00:01
   ---------------------------------------  98.0/100.2 MB 3.7 MB/s eta 0:00:01
   ---------------------------------------  98.6/100.2 MB 3.7 MB/s eta 0:00:01
   ---------------------------------------  99.4/100.2 MB 3.7 MB/s eta 0:00:01
   ---------------------------------------  100.1/100.2 MB 3.7 MB/s eta 0:00:01
   ---------------------------------------- 100.2/100.2 MB 3.6 MB/s eta 0:00:00
Downloading graphviz-0.21-py3-none-any.whl (47 kB)
Installing collected packages: graphviz, catboost

   -------------------- ------------------- 1/2 [catboost]
   -------------------- ------------------- 1/2 [catboost]
   -------------------- ------------------- 1/2 [catboost]
   -------------------- ------------------- 1/2 [catboost]
   -------------------- ------------------- 1/2 [catboost]
   -------------------- ------------------- 1/2 [catboost]
   -------------------- ------------------- 1/2 [catboost]
   -------------------- ------------------- 1/2 [catboost]
   -------------------- ------------------- 1/2 [catboost]
   -------------------- ------------------- 1/2 [catboost]
   ---------------------------------------- 2/2 [catboost]

Successfully installed catboost-1.2.10 graphviz-0.21

In [82]:
from catboost import CatBoostRegressor

In [83]:
cat_features = X.select_dtypes(include='object').columns.tolist()
cat_features

['location',
 'fuel_type',
 'transmission_type',
 'owner_type',
 'brand',
 'model',
 'seller_type']

In [85]:
from catboost import CatBoostRegressor
from sklearn.model_selection import train_test_split

# 1️⃣ Define X and y
X = df.drop(columns=['price_inr', 'car_name'])
y = df['price_inr']

# 2️⃣ Tell CatBoost which columns are categorical
cat_features = X.select_dtypes(include='object').columns.tolist()

# 3️⃣ Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# 4️⃣ Create model
cat_model = CatBoostRegressor(
    iterations=3000,
    learning_rate=0.05,
    depth=10,
    loss_function='RMSE',
    eval_metric='RMSE',
    random_seed=42,
    verbose=200
)

# 5️⃣ Train
cat_model.fit(
    X_train, y_train,
    cat_features=cat_features,
    eval_set=(X_test, y_test)
)

0:	learn: 883951.9676039	test: 1116977.1328811	best: 1116977.1328811 (0)	total: 211ms	remaining: 10m 33s
200:	learn: 241691.4083496	test: 699678.8688157	best: 699678.8688157 (200)	total: 19.4s	remaining: 4m 30s
400:	learn: 196192.5828874	test: 692190.7516813	best: 691602.1217288 (393)	total: 38.3s	remaining: 4m 7s
600:	learn: 165846.0953182	test: 688314.0682553	best: 688314.0682553 (600)	total: 57.1s	remaining: 3m 47s
800:	learn: 146027.9151907	test: 686577.4624760	best: 686217.7903268 (775)	total: 1m 16s	remaining: 3m 29s
1000:	learn: 132700.7376020	test: 685774.9016636	best: 685774.9016636 (1000)	total: 1m 35s	remaining: 3m 10s
1200:	learn: 122670.5275760	test: 684301.8723752	best: 684272.3469522 (1194)	total: 1m 54s	remaining: 2m 51s
1400:	learn: 115350.9448685	test: 683636.7464130	best: 683563.2296744 (1383)	total: 2m 13s	remaining: 2m 32s
1600:	learn: 108469.6498000	test: 683146.1726022	best: 683127.6369984 (1571)	total: 2m 32s	remaining: 2m 13s
1800:	learn: 103401.1608414	test: 683037.2937807	best: 683037.2937807 (1800)	total: 2m 52s	remaining: 1m 54s
2000:	learn: 98707.3432301	test: 683148.4233957	best: 682936.0571120 (1867)	total: 3m 11s	remaining: 1m 35s
2200:	learn: 94293.4384783	test: 683098.8554365	best: 682909.0980898 (2067)	total: 3m 31s	remaining: 1m 16s
2400:	learn: 90918.8344518	test: 682881.6185845	best: 682879.9027340 (2399)	total: 3m 50s	remaining: 57.6s
2600:	learn: 87484.4373504	test: 682975.1153756	best: 682730.3076786 (2466)	total: 4m 10s	remaining: 38.4s
2800:	learn: 84236.3669262	test: 682846.0075226	best: 682730.3076786 (2466)	total: 4m 30s	remaining: 19.2s
2999:	learn: 81462.1260132	test: 682872.7390925	best: 682730.3076786 (2466)	total: 4m 49s	remaining: 0us

bestTest = 682730.3077
bestIteration = 2466

Shrink model to first 2467 iterations.

CatBoostRegressor(depth=10, eval_metric='RMSE', iterations=3000, learning_rate=0.05, loss_function='RMSE', random_seed=42, verbose=200)

In [86]:
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
import numpy as np

# Predict
y_pred = cat_model.predict(X_test)

# Metrics
r2 = r2_score(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
mape = np.mean(np.abs((y_test - y_pred) / y_test)) * 100

print("R2:", r2)
print("MAE:", mae)
print("RMSE:", rmse)
print("MAPE:", mape)

R2: 0.6436967357952512
MAE: 124055.70447234262
RMSE: 682730.307678591
MAPE: 13.455863434487208

In [87]:
y_log = np.log1p(y)

X_train, X_test, y_train, y_test = train_test_split(
    X, y_log, test_size=0.2, random_state=42
)

cat_model = CatBoostRegressor(
    iterations=3000,
    learning_rate=0.05,
    depth=10,
    loss_function='RMSE',
    eval_metric='RMSE',
    random_seed=42,
    verbose=200
)

cat_model.fit(
    X_train, y_train,
    cat_features=cat_features,
    eval_set=(X_test, y_test)
)

0:	learn: 0.7131254	test: 0.7295941	best: 0.7295941 (0)	total: 99.6ms	remaining: 4m 58s
200:	learn: 0.1864332	test: 0.2022181	best: 0.2022181 (200)	total: 18.6s	remaining: 4m 19s
400:	learn: 0.1649522	test: 0.1893506	best: 0.1893506 (400)	total: 37.2s	remaining: 4m 1s
600:	learn: 0.1531572	test: 0.1847876	best: 0.1847876 (600)	total: 55.9s	remaining: 3m 43s
800:	learn: 0.1448072	test: 0.1822365	best: 0.1822365 (800)	total: 1m 14s	remaining: 3m 25s
1000:	learn: 0.1383108	test: 0.1811358	best: 0.1811358 (1000)	total: 1m 33s	remaining: 3m 7s
1200:	learn: 0.1329104	test: 0.1804614	best: 0.1804441 (1195)	total: 1m 52s	remaining: 2m 48s
1400:	learn: 0.1283656	test: 0.1800693	best: 0.1800623 (1398)	total: 2m 12s	remaining: 2m 31s
1600:	learn: 0.1241844	test: 0.1797285	best: 0.1797285 (1600)	total: 2m 35s	remaining: 2m 15s
1800:	learn: 0.1203185	test: 0.1791826	best: 0.1791691 (1798)	total: 2m 55s	remaining: 1m 56s
2000:	learn: 0.1169780	test: 0.1789169	best: 0.1789163 (1999)	total: 3m 16s	remaining: 1m 38s
2200:	learn: 0.1136127	test: 0.1789461	best: 0.1788331 (2077)	total: 3m 38s	remaining: 1m 19s
2400:	learn: 0.1108595	test: 0.1788515	best: 0.1788279 (2337)	total: 3m 58s	remaining: 59.6s
2600:	learn: 0.1083528	test: 0.1788315	best: 0.1788224 (2587)	total: 4m 19s	remaining: 39.7s
2800:	learn: 0.1058238	test: 0.1787895	best: 0.1787449 (2735)	total: 4m 39s	remaining: 19.9s
2999:	learn: 0.1034142	test: 0.1787688	best: 0.1787449 (2735)	total: 5m	remaining: 0us

bestTest = 0.1787449075
bestIteration = 2735

Shrink model to first 2736 iterations.

CatBoostRegressor(depth=10, eval_metric='RMSE', iterations=3000, learning_rate=0.05, loss_function='RMSE', random_seed=42, verbose=200)

In [88]:
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
import numpy as np

# Predict in log space
y_pred_log = cat_model.predict(X_test)

# Convert back to original price
y_pred = np.expm1(y_pred_log)
y_true = np.expm1(y_test)

# Metrics
r2 = r2_score(y_true, y_pred)
mae = mean_absolute_error(y_true, y_pred)
rmse = np.sqrt(mean_squared_error(y_true, y_pred))
mape = np.mean(np.abs((y_true - y_pred) / y_true)) * 100

print("R2:", r2)
print("MAE:", mae)
print("RMSE:", rmse)
print("MAPE:", mape)

R2: 0.6343460979415376
MAE: 122487.14432984425
RMSE: 691630.9000691455
MAPE: 12.829619527290447

In [89]:
cat_model.save_model("used_car_price_model.cbm")

In [90]:
from catboost import CatBoostRegressor

loaded_model = CatBoostRegressor()
loaded_model.load_model("used_car_price_model.cbm")

CatBoostRegressor(depth=10, eval_metric='RMSE', iterations=3000, learning_rate=0.05, loss_function='RMSE', random_seed=42, verbose=200)

In [91]:
import pandas as pd

sample = pd.DataFrame([{
    'location': 'Chennai',
    'km_driven': 50000,
    'fuel_type': 'Petrol',
    'transmission_type': 'Manual',
    'owner_type': 'First',
    'mileage': 18.0,
    'engine': 1197,
    'max_power': 82,
    'seats': 5,
    'vehicle_age': 5,
    'brand': 'Hyundai',
    'model': 'i20',
    'seller_type': 'Dealer'
}])

sample

,location,km_driven,fuel_type,transmission_type,owner_type,mileage,engine,max_power,seats,vehicle_age,brand,model,seller_type
0,Chennai,50000,Petrol,Manual,First,18.0,1197,82,5,5,Hyundai,i20,Dealer

In [92]:
pred_price = loaded_model.predict(sample)

print("Predicted Price ₹:", int(pred_price[0]))

Predicted Price ₹: 13

In [93]:
import numpy as np

pred_price = loaded_model.predict(sample)

real_price = np.expm1(pred_price)

print("Predicted Price ₹:", int(real_price[0]))

Predicted Price ₹: 619720

In [95]:
!pip install streamlit

Requirement already satisfied: streamlit in c:\users\sunil\anaconda3\lib\site-packages (1.45.1)
Requirement already satisfied: altair<6,>=4.0 in c:\users\sunil\anaconda3\lib\site-packages (from streamlit) (5.5.0)
Requirement already satisfied: blinker<2,>=1.5.0 in c:\users\sunil\anaconda3\lib\site-packages (from streamlit) (1.9.0)
Requirement already satisfied: cachetools<6,>=4.0 in c:\users\sunil\anaconda3\lib\site-packages (from streamlit) (5.5.1)
Requirement already satisfied: click<9,>=7.0 in c:\users\sunil\anaconda3\lib\site-packages (from streamlit) (8.1.8)
Requirement already satisfied: numpy<3,>=1.23 in c:\users\sunil\anaconda3\lib\site-packages (from streamlit) (2.1.3)
Requirement already satisfied: packaging<25,>=20 in c:\users\sunil\anaconda3\lib\site-packages (from streamlit) (24.2)
Requirement already satisfied: pandas<3,>=1.4.0 in c:\users\sunil\anaconda3\lib\site-packages (from streamlit) (2.2.3)
Requirement already satisfied: pillow<12,>=7.1.0 in c:\users\sunil\anaconda3\lib\site-packages (from streamlit) (11.1.0)
Requirement already satisfied: protobuf<7,>=3.20 in c:\users\sunil\anaconda3\lib\site-packages (from streamlit) (6.33.5)
Requirement already satisfied: pyarrow>=7.0 in c:\users\sunil\anaconda3\lib\site-packages (from streamlit) (19.0.0)
Requirement already satisfied: requests<3,>=2.27 in c:\users\sunil\anaconda3\lib\site-packages (from streamlit) (2.32.3)
Requirement already satisfied: tenacity<10,>=8.1.0 in c:\users\sunil\anaconda3\lib\site-packages (from streamlit) (9.0.0)
Requirement already satisfied: toml<2,>=0.10.1 in c:\users\sunil\anaconda3\lib\site-packages (from streamlit) (0.10.2)
Requirement already satisfied: typing-extensions<5,>=4.4.0 in c:\users\sunil\anaconda3\lib\site-packages (from streamlit) (4.12.2)
Requirement already satisfied: watchdog<7,>=2.1.5 in c:\users\sunil\anaconda3\lib\site-packages (from streamlit) (4.0.2)
Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in c:\users\sunil\anaconda3\lib\site-packages (from streamlit) (3.1.43)
Requirement already satisfied: tornado<7,>=6.0.3 in c:\users\sunil\anaconda3\lib\site-packages (from streamlit) (6.5.1)
Requirement already satisfied: jinja2 in c:\users\sunil\anaconda3\lib\site-packages (from altair<6,>=4.0->streamlit) (3.1.6)
Requirement already satisfied: jsonschema>=3.0 in c:\users\sunil\anaconda3\lib\site-packages (from altair<6,>=4.0->streamlit) (4.23.0)
Requirement already satisfied: narwhals>=1.14.2 in c:\users\sunil\anaconda3\lib\site-packages (from altair<6,>=4.0->streamlit) (1.31.0)
Requirement already satisfied: colorama in c:\users\sunil\anaconda3\lib\site-packages (from click<9,>=7.0->streamlit) (0.4.6)
Requirement already satisfied: gitdb<5,>=4.0.1 in c:\users\sunil\anaconda3\lib\site-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.7)
Requirement already satisfied: smmap<5,>=3.0.1 in c:\users\sunil\anaconda3\lib\site-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\sunil\anaconda3\lib\site-packages (from pandas<3,>=1.4.0->streamlit) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\sunil\anaconda3\lib\site-packages (from pandas<3,>=1.4.0->streamlit) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\sunil\anaconda3\lib\site-packages (from pandas<3,>=1.4.0->streamlit) (2025.2)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\sunil\anaconda3\lib\site-packages (from requests<3,>=2.27->streamlit) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\sunil\anaconda3\lib\site-packages (from requests<3,>=2.27->streamlit) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\sunil\anaconda3\lib\site-packages (from requests<3,>=2.27->streamlit) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\sunil\anaconda3\lib\site-packages (from requests<3,>=2.27->streamlit) (2025.4.26)
Requirement already satisfied: attrs>=22.2.0 in c:\users\sunil\anaconda3\lib\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (24.3.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\users\sunil\anaconda3\lib\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (2023.7.1)
Requirement already satisfied: referencing>=0.28.4 in c:\users\sunil\anaconda3\lib\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (0.30.2)
Requirement already satisfied: rpds-py>=0.7.1 in c:\users\sunil\anaconda3\lib\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (0.22.3)
Requirement already satisfied: six>=1.5 in c:\users\sunil\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas<3,>=1.4.0->streamlit) (1.17.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\sunil\anaconda3\lib\site-packages (from jinja2->altair<6,>=4.0->streamlit) (3.0.2)

In [97]:
df.to_csv("cleaned_car_data.csv", index=False)

In [5]:
import os
os.listdir()

['.ipynb_checkpoints',
 'cardekho_dataset.csv',
 'car_columns.pkl',
 'car_price_app.py',
 'car_price_model.pkl',
 'catboost_info',
 'cleaned_car_data.csv',
 'encoders.pkl',
 'used car price prediction.ipynb',
 'used_cars_data.csv',
 'used_car_price_model.cbm']

In [6]:
os.getcwd()

'C:\\Users\\sunil\\projects\\used car price prediction'